env:
  global:
    - GITHUB_REPO: github.com/NoName4Me/noname4me.github.io.git
language:
  node_js
node_js:
  - "8"
install:
  - npm install -g yarn
script:
  - yarn
  - yarn docs:build
after_script:
  - git clone "https://${GITHUB_TOKEN}@${GITHUB_REPO}"
  - cd noname4me.github.io
  - mkdir -p solutions/paper-ui
  - cp -R ../docs/.vuepress/dist/* solutions/paper-ui/
  - git add .
  - git commit -m "update Paper UI"
  - git push